### PR TITLE
Dockerfile for MPLABX toolchain

### PR DESCRIPTION
**Pull request by davidjsherman**
This Dockerfile defines an image for a Jenkins slave node with MPLABX's `xc16` cross-compiler, including the PIC24/dsPIC Peripheral Libraries.

The container's default entrypoint will start a Jenkins slave. To run an interactive shell, use:
```
docker run -it -w /var/jenkins_home --entrypoint /bin/bash aseba/mplabx
```
This container is intended to be compatible with #29 .

### CODE REVIEW

**Comment by davidjsherman** [comment]
The following should, but currently doesn't, work:
```
git clone https://github.com/aseba-community/aseba.git
git clone https://github.com/aseba-community/aseba-target-thymio2.git
cd aseba-target-thymio2
git fetch origin pull/29/head:build_system
git checkout build_system
git submodule update --init
mkdir -p build && cd build
cmake -DASEBA_DIR=$HOME/aseba ..
make
```

**Comment by cor3ntin** [comment]
For some reason, /etc/profile.d is not read from - PATH is therefore not set. investigating.

**Comment by cor3ntin** [comment]
I'm afraid I have been misleading you.
cmake actually looks for xc16 at a known location /opt/microchip/v.xx
The following scripts work - use of ninja is optional.



```
FROM jenkins

USER root

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja \
    curl \
    gcc-multilib \
    git \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Allow sudo by user 'jenkins' without password
RUN gpasswd -a jenkins sudo && \
    sed -i.bkp -e \
      's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' \
      /etc/sudoers

# Retrieve XC16 compiler and install headless
RUN curl -fSL -A 'Mozilla/5.0' -o /tmp/xc16-install.run \
        'http://www.microchip.com/mplabxc16linux' && \
    chmod a+x /tmp/xc16-install.run && \
    /tmp/xc16-install.run --prefix /opt/microchip/xc16/v1.33 \
        --mode unattended --unattendedmodeui none \
        --netservername localhost --LicenseType FreeMode && \
    rm -f /tmp/xc16-install.run

# Retrieve PIC24/dsPIC Peripheral Libraries and install headless
RUN curl -fSL -A 'Mozilla/5.0' -o /tmp/plib16-install.run \
    'http://ww1.microchip.com/downloads/en/DeviceDoc/peripheral-libraries-for-pic24-and-dspic-v2.00-linux-installer.run' && \
    chmod a+x /tmp/plib16-install.run && \
    /tmp/plib16-install.run --prefix /opt/microchip/xc16/v1.33 \
        --mode unattended --unattendedmodeui none && \
    rm -f /tmp/plib16-install.run

USER jenkins
```



```
git clone https://github.com/aseba-community/aseba.git --depth=1
git clone https://github.com/aseba-community/aseba-target-thymio2.git --depth=1 --recursive
cd aseba-target-thymio2
git fetch origin pull/29/head:build_system
git checkout build_system
git submodule update --init
mkdir -p build && cd build
cmake -DASEBA_DIR=$HOME/aseba -GNinja ..
ninja
```

**Comment by davidjsherman** [comment]
@cor3ntin `docker run -it -w /var/jenkins_home aseba/mplabx /bin/bash --login`

**Comment by davidjsherman** [comment]
It would be better if the CMake module looked for the installation directory, otherwise why use CMake?
For example, using the path of the `xc16` executable.

**Comment by davidjsherman** [comment]
@cor3ntin As a failsafe, I added a self link for the version, determined from the installation.

It compiles #29 but I don't know whether the result is correct; the MD5 sum is<br/>362fb0235b07f189f63f6200e5397806  aseba-target-thymio2

**Comment by cor3ntin** [comment]
We need to ask @mbonani to test the builded firmware.

**Comment by davidjsherman** [comment]
@mbonani This container doesn't try to install a license because I am assuming that the goal is only to compile and test the firmware during development. Compiling the final version with full optimization would be done by Mobsya. Do you agree?

**Comment by mbonani** [comment]
Thanks

**Pull request merged**
